server/web/models.py
from datetime import datetime

from flask_login import UserMixin
from flask import current_app

from . import db


class UserModel(UserMixin, db.Model):
    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), nullable=False)
    password = db.Column(db.String(30), nullable=False)


class AccountModel(db.Model):
    __tablename__ = "wax_account"

    id = db.Column(db.Integer, primary_key=True)
    private_token = db.Column(db.String(100), nullable=False, unique=True)
    name = db.Column(db.String(12), nullable=False, unique=True)
    atomic_drop_balance = db.Column(db.Float)
    nefty_drop_balance = db.Column(db.Float)
    balance = db.Column(db.Float)
    cpu = db.Column(db.Float)
    ram = db.Column(db.Float)
    update_time = db.Column(db.DateTime, default=datetime.now())
    rpc = db.Column(db.String(), nullable=False)

    # disabled = False



class Settings(db.Model):
    __tablename__ = "settings"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True)
    key = db.Column(db.String, nullable=False, unique=True)
    current = db.Column(db.String, nullable=False)
    value = db.Column(db.String)
    is_input = db.Column(db.Boolean, default=True)
    is_select = db.Column(db.Boolean, default=False)
    is_check = db.Column(db.Boolean, default=False)


def has_no_empty_params(rule):
    defaults = rule.defaults if rule.defaults is not None else ()
    arguments = rule.arguments if rule.arguments is not None else ()
    return len(defaults) >= len(arguments)


db.create_all(app=current_app)

server/web/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from flask_jsglue import JSGlue

from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate

import redis

from .utils import check_db_file
from .jinja_utils import cstm_context_processor


db = SQLAlchemy()
migrate = Migrate()

url = "https://testnet.waxsweden.org"
contract_account = "neftyblocksd"

redis_client = redis.Redis()


def create_app():
    app = Flask(__name__)
    app.config.from_object('web.config.DevelopConfig')
    app.app_context().push()

    db.init_app(app)
    migrate.init_app(app, db)

    socketio = SocketIO()
    socketio.init_app(app)

    jsglue = JSGlue()
    jsglue.init_app(app)

    # Login manager
    from .models import UserModel
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        # since the user_id is just the primary key of our user table, use it in the query for the user
        return UserModel.query.get(int(user_id))

    # blueprint for utils
    from .utils import utils
    app.register_blueprint(utils)


    # blueprint for main
    from .main import main
    app.register_blueprint(main)

    # blueprint for main
    from .settings import settings
    app.register_blueprint(settings)

    # blueprint for manage
    from .manage import manage
    app.register_blueprint(manage)

    # blueprint for main
    from .api import api
    app.register_blueprint(api)

    # blueprint for websocket
    from .manage import script_ws
    app.register_blueprint(script_ws)

    @app.context_processor
    def context_processor():
        return cstm_context_processor()

    return app

server/web/api/__init__.py
from .api import api


from .manage import manage
api.register_blueprint(manage)

server/web/blueprintio.py
import socketio

from flask import Blueprint


class IOBlueprint(Blueprint):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.namespace = self.url_prefix or '/'
        self._socketio_handlers = []
        self.socketio = None
        self.record_once(self.init_socketio)

    def init_socketio(self, state):
        self.socketio: socketio.Client = state.app.extensions['socketio']
        for f in self._socketio_handlers:
            f(self.socketio)

        return self.socketio

    def on(self, key):
        """ A decorator to add a handler to a blueprint. """

        def wrapper(f):
            def wrap(sio):
                @sio.on(key, namespace=self.namespace)
                def wrapped(*args, **kwargs):
                    return f(*args, **kwargs)

                return sio

            self._socketio_handlers.append(wrap)

        return wrapper

    def emit(self, *args, **kwargs):
        self.socketio.emit(*args, **kwargs)

server/web/main.py
from flask import Blueprint
from flask import render_template

from .models import AccountModel

from .settings import Settings


main = Blueprint('main', __name__)


@main.route('/')
def index_view():
    settings = Settings()
    rpc_url = settings.rpc_url.current
    contract_account = settings.contract_account.current
    accounts = AccountModel.query.filter_by(rpc=rpc_url).all()
    return render_template("index.html",
                           rpc_url=rpc_url,
                           contract_account=contract_account,
                           accounts=accounts)


@main.route('/add-accounts')
def add_accounts_view():
    return render_template("add-accounts.html")

server/web/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom-style.css') }}">

    {{ JSGlue.include() }}
</head>
<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0 main_name" href="/"><h2>SERBER BOT</h2></a>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky custom-sidebar">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('main.index_view') }}">
                            <span data-feather="home"></span>
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('settings.settings_view') }}">
                            <span data-feather="settings"></span>
                            Settings
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Manage</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manage.claimdrop.claimdrop_view') }}">
                            <span data-feather="circle"></span>
                            Claimdrop
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            {% block body %}

            {% endblock %}
        </main>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.2/umd/popper.min.js"
        integrity="sha512-aDciVjp+txtxTJWsp8aRwttA0vR2sJMk/73ZT7ExuEHv7I5E6iyyobpFOlEFkq59mWW8ToYGuVZFnwhwIUisKA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>


{% block scripts %}

{% endblock %}


</body>
</html>

server/web/templates/index.html
{% extends "base.html" %}

{% block title %}SERBER - main{% endblock %}

{% block body %}



    <h5>Current contract: <i>{{ contract_account }}</i></h5>
    <h5>Current RPC: <i>{{ rpc_url }}</i></h5>
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Updated</th>
            <th scope="col">Balance</th>
            <th scope="col">Drop Balance</th>
            <th scope="col">Staked CPU</th>
            <th scope="col">Staked RAM</th>
            <th scope="col">Key</th>
        </tr>
        </thead>
        <tbody>
        {% for account in accounts %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.update_time.strftime('%d %b, %H:%M:%S') }}</td>
                <td>{{ account.balance }}</td>
                {% if contract_account == "neftyblocksd" %}
                    <td>{{ account.nefty_drop_balance }}</td>
                {% elif contract_account == "atomicdropsx" %}
                    <td>{{ account.atomic_drop_balance }}</td>
                {% endif %}
                <td>{{ account.cpu }}%</td>
                <td>{{ account.ram }}%</td>
                <td>...{{ account.private_token[-10:] }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="btn btn-primary" name="update_button" id="update_button">Update</button>
    <br>
    <br>


    <h4>Add account</h4>
    <br>
    <div class="row">
        <div class="col">
            <form method="post" action="{{ url_for('api.set_keys') }}">
                <div class="form-group">
                    <textarea name="private_keys_placeholder" class="form-control" id="private_keys_placeholder"
                              rows="5"></textarea>
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col">

        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function () {
            // Listen to click event on the submit button
            $('#update_button').click(function (e) {

                e.preventDefault();


                $.ajax({
                    type: "POST",
                    url: Flask.url_for('api.update_accs_info'),
                    dataType: "json",
                    success: function (result) {
                        console.log("Request sended")
                    },
                    error: function (result) {
                        console.log("Error while sending request: " + result)
                    }
                })
                console.log("Sending request...")
            });
        });
    </script>
{% endblock %}

server/web/templates/settings.html
{% extends "base.html" %}


{% block title %}SERBER - settings{% endblock %}


{% block body %}
    <h3>Settings</h3>
    <form action="{{ url_for("settings.set") }}" method="POST">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Current</th>
                <th scope="col">Choose</th>
            </tr>
            </thead>

            <tbody>
            {% for item in settings %}
                <tr>
                    <td>
                        {{ item.name }}
                    </td>
                    <td>
                        {{ item.current }}
                    </td>
                    <td>
                        <div class="form-group">
                            {% if item.is_input %}
                                <input type="text" class="form-control" id="{{ item.key }}_input"
                                       name="{{ item.key }}" placeholder="{{ item.value }}">

                            {% elif item.is_select %}
                                {% set value = json_loads(item.value) %}
                                <select class="form-control" id="{{ item.key }}_select" name="{{ item.key }}">
                                    {% for item in value %}
                                        <option value="{{ item.value }}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>

                            {% endif %}

                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}